# Generated by Django 3.0.4 on 2020-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLID', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLID', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLID', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10),
        ),
    ]
